apiVersion: v1
kind: Service
metadata:
  name: {{ include "echobe.fullname" . }}-service
  labels:
    app.kubernetes.io/name: {{ include "echobe.name" . }}
    helm.sh/chart: {{ include "echobe.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "echobe.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: grpc
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
